### ISSUE TITLE
I cannot retrieve my own information. I

### ISSUE THREAD

**Issue by huseyincenik** [spider-man-tm/kaggle-badges#17]
Hello, I uploaded the Kaggle badge to my profile. However, the information that is retrieved is related to your Kaggle statistics. I cannot retrieve my own information. I am waiting for your help in this regard.

https://github.com/huseyincenik/huseyincenik/blob/main/.github/workflows

**Comment by spider-man-tm** [comment]
@huseyincenik 

The issue is likely caused by an incorrect workflow path. Please try the following steps:

1. Change the path of the YAML file:
`./github/workflows` → `.github/workflows/hogefuga.yml`

2. Add permissions to edit the workflow for the repository (https://github.com/marketplace/actions/kaggle-badges#2-set-workflow-permissions)

3. Re-run the workflow

**Comment by huseyincenik** [comment]
Thank you. It is solved
